# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myaims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 7, 0, 49, 47856, tzinfo=utc)),
        ),
    ]
