# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myaims', '0002_auto_20160608_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='t_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='t_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='aim',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 7, 13, 49, 481656, tzinfo=utc)),
        ),
    ]
